### ISSUE TITLE
We were unable to create a working story

### ISSUE THREAD

**Issue by ilwsm** [Liareth/BG3Mods#6]
After installing mod via `BG3ModManager` i have this message:
``` "We were unable to create a working story. Your add-on setup might be invalid. The game will continue with the setup from the savegame." ```
Is it normal?

**Comment by Liareth** [comment]
Yes.

**Comment by ilwsm** [comment]
Thanks. 
And yet, in the first act: the goblin merchant has no bags, Aaron only has.
Game version: current steam version.
